interface Chart {
    airport: string,
    author: string,
    id: number,
    category: "GEN" | "GND" | "SID" | "STAR" | "APP",
    name: string,
    file: string,
    runways: string[],
}
let charts: Chart[] = [
    {
        airport: "ITEST",
        author: "nobody",
        id: 41421242,
        category: "GND",
        name: "no",
        file: "",
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 0,
        category: "GND",
        name: "A380 Ground Movement",
        file: '/charts/tokyo/nikita39_ryse/a388 movement chart.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 1,
        category: "GND",
        name: "B747 A340 Ground Movement",
        file: '/charts/tokyo/nikita39_ryse/b744 a346 movement chart.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 2,
        category: "GND",
        name: "B767 B777 B787 A330 A350 MD11 Ground Movement",
        file: '/charts/tokyo/nikita39_ryse/b676 etc movement chart.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 3,
        category: "GND",
        name: "Aerodrome Chart",
        file: '/charts/tokyo/nikita39_ryse/aerodrome chart.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 4,
        category: "GND",
        name: "Parking Chart",
        file: '/charts/tokyo/nikita39_ryse/parking chart.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 5,
        category: "GEN",
        name: "Airport Information",
        file: '/charts/tokyo/nikita39_ryse/airport information.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 6,
        category: "GEN",
        name: "Airport Briefing 1",
        file: '/charts/tokyo/nikita39_ryse/airport briefing 1.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 7,
        category: "GEN",
        name: "Airport Briefing 2",
        file: '/charts/tokyo/nikita39_ryse/airport briefing 2.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 8,
        category: "GEN",
        name: "Airport Briefing 3",
        file: '/charts/tokyo/nikita39_ryse/airport briefing 3.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 9,
        category: "GEN",
        name: "radar minimum altitude",
        file: '/charts/tokyo/nikita39_ryse/radar min alt.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 10,
        category: "GEN",
        name: "approach control area",
        file: '/charts/tokyo/nikita39_ryse/tma.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 11,
        category: "GEN",
        name: "control zone and control area",
        file: '/charts/tokyo/nikita39_ryse/vfr.jpg',
        runways: [],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 12,
        category: "SID",
        name: "RNAV RWY 02 BLANK 1W EURAD 1W HONDA 1W ONDER 1W RENDR 1W",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad honda onder rendr 1w.jpg',
        runways: ["02"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 13,
        category: "SID",
        name: "RNAV RWY 13 BLANK 1X EURAD 1X HONDA 1X ONDER 1X RENDR 1X",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad honda onder rendr 1x.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 14,
        category: "SID",
        name: "RNAV RWY 20 BLANK 1Y EURAD 1Y HONDA 1Y ONDER 1Y RENDR 1Y",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad honda onder rendr 1y.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 15,
        category: "SID",
        name: "RNAV RWY 31 BLANK 1Z EURAD 1Z HONDA 1Z ONDER 1Z RENDR 1Z",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad honda onder rendr 1z.jpg',
        runways: ["31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 16,
        category: "SID",
        name: "RNAV RWY 02/13 BLANK 2A 2b EURad 2a 2b",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad 2a 2b.jpg',
        runways: ["02", "13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 17,
        category: "SID",
        name: "RNAV RWY 20/31 BLANK 2c 2d EURad 2c 2d",
        file: '/charts/tokyo/nikita39_ryse/sid blank eurad 2c 2d.jpg',
        runways: ["20", "31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 18,
        category: "SID",
        name: "RNAV RWY 02/31 ONDER 2A 2d RENDR 2a 2d",
        file: '/charts/tokyo/nikita39_ryse/sid onder rendr 2a 2d.jpg',
        runways: ["02", "31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 19,
        category: "SID",
        name: "RNAV RWY 13/20 onder 2b 2c rendr 2b 2c",
        file: '/charts/tokyo/nikita39_ryse/sid onder rendr 2b 2c.jpg',
        runways: ["13", "20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 20,
        category: "STAR",
        name: "RNAV RWY 13 blank 1h eurad 1h honda 1h onder 1h rendr1h",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad honda onder rendr 1h.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 21,
        category: "STAR",
        name: "RNAV RWY 13 honda 1p 2h onder 1p",
        file: '/charts/tokyo/nikita39_ryse/star honda 1p 2h onder 1p.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 22,
        category: "STAR",
        name: "RNAV RWY 20 blank 1e eurad 1e honda 1e onder 1e rendr1e",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad honda onder rendr 1e.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 23,
        category: "STAR",
        name: "RNAV RWY 20 blank 1n 1s eurad 1n 1s",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad 1n 1s.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 24,
        category: "STAR",
        name: "RNAV RWY 31 blank 1k eurad 1k honda 1k onder 1k rendr1k",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad honda onder rendr 1k.jpg',
        runways: ["31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 25,
        category: "STAR",
        name: "RNAV RWY 31 BLANK 1l eurad 1l honda 1l",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad honda 1l.jpg',
        runways: ["31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 26,
        category: "STAR",
        name: "RWY 13/20/31 blank 1o eurad 1o honda 1o onder 1o rendr1o",
        file: '/charts/tokyo/nikita39_ryse/star blank eurad honda onder rendr 1o.jpg',
        runways: ["13", "20", "31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 27,
        category: "APP",
        name: "ILS/LOC RWY 13",
        file: '/charts/tokyo/nikita39_ryse/ils loc 13.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 28,
        category: "APP",
        name: "LDA RWY 13",
        file: '/charts/tokyo/nikita39_ryse/lda 13.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 29,
        category: "APP",
        name: "RNP RWY 13",
        file: '/charts/tokyo/nikita39_ryse/rnp 13.jpg',
        runways: ["13"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 30,
        category: "APP",
        name: "ILS Y/LOC Y RWY 20",
        file: '/charts/tokyo/nikita39_ryse/ils y loc y 20.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 31,
        category: "APP",
        name: "ILS Z/LOC Z RWY 20",
        file: '/charts/tokyo/nikita39_ryse/ils z loc z 20.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 32,
        category: "APP",
        name: "RNP RWY 20",
        file: '/charts/tokyo/nikita39_ryse/rnp 20.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 33,
        category: "APP",
        name: "HIGHWAY VISUAL RWY 20",
        file: '/charts/tokyo/nikita39_ryse/highway visual 20.jpg',
        runways: ["20"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 34,
        category: "APP",
        name: "ILS DME Y/LOC DME Y RWY 31",
        file: '/charts/tokyo/nikita39_ryse/ils dme y loc dme y 31.jpg',
        runways: ["31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 35,
        category: "APP",
        name: "ILS DME Z/LOC DME Z RWY 31",
        file: '/charts/tokyo/nikita39_ryse/ils dme z loc dme z 31.jpg',
        runways: ["31"],
    },
    {
        airport: "ITKO",
        author: "Nikita39Gamer & RyoboyRYO",
        id: 36,
        category: "APP",
        name: "RNP RWY 31",
        file: '/charts/tokyo/nikita39_ryse/rnp 31.jpg',
        runways: ["31"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 37,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barthelemy/sweet/aerodrome chart.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 38,
        category: "STAR",
        name: "rnav rwy 27 silva 1",
        file: '/charts/barthelemy/sweet/star silva 1.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 39,
        category: "STAR",
        name: "rnav rwy 27 camel 1",
        file: '/charts/barthelemy/sweet/star camel 1.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 40,
        category: "STAR",
        name: "rnav rwy 27 rom 1",
        file: '/charts/barthelemy/sweet/star romens 1.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 41,
        category: "STAR",
        name: "rnav rwy 09 rom 1",
        file: '/charts/barthelemy/sweet/star gavin 1.jpg',
        runways: ["09"],
    },

    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 42,
        category: "STAR",
        name: "rnav rwy 09 rom 1",
        file: '/charts/barthelemy/sweet/star welsh 1.jpg',
        runways: ["09"],
    },

    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 43,
        category: "STAR",
        name: "rnav rwy 09 rom 1",
        file: '/charts/barthelemy/sweet/star diner 1.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 44,
        category: "APP",
        name: "ils/loc rwy 09",
        file: '/charts/barthelemy/sweet/ils loc 09.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 45,
        category: "APP",
        name: "ils/loc rwy 27",
        file: '/charts/barthelemy/sweet/ils loc 27.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 46,
        category: "SID",
        name: "rnav rwy 09 vox 1",
        file: '/charts/barthelemy/sweet/sid vox 1.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 47,
        category: "SID",
        name: "rnav rwy 09 montn 1",
        file: '/charts/barthelemy/sweet/sid montn 1.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 48,
        category: "SID",
        name: "rnav rwy 27 res 1",
        file: '/charts/barthelemy/sweet/sid res 1.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 49,
        category: "SID",
        name: "rnav rwy 27 ocean 1",
        file: '/charts/barthelemy/sweet/sid ocean 1.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "sweet_kid",
        id: 50,
        category: "SID",
        name: "rwy 09/27 sbh 1",
        file: '/charts/barthelemy/sweet/sid sbh 1.jpg',
        runways: ["09", "27"],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 51,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barthelemy/alisoe/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 52,
        category: "GEN",
        name: "aerodrome obstacle chart",
        file: '/charts/barthelemy/alisoe/obstacle.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 53,
        category: "SID",
        name: "rnav rwy 09 rom 1p silva 1p oceen 1p index 1p 1q",
        file: '/charts/barthelemy/alisoe/sid 1p 1q.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 54,
        category: "SID",
        name: "rnav rwy 27 rom 2j silva 2j oceen 2j vox 2j index 2j",
        file: '/charts/barthelemy/alisoe/sid 2j.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 55,
        category: "STAR",
        name: "rnav rwy 09 rom 2m index 2m oceen 2m silva 2m vox 2m",
        file: '/charts/barthelemy/alisoe/star 2m.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "Alisoe",
        id: 56,
        category: "STAR",
        name: "rnav rwy 27 rom 2v index 2v 2x oceen 2v silva 2v res 2x",
        file: '/charts/barthelemy/alisoe/star 2v 2x.jpg',
        runways: ["27"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 57,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/grindavik/formicacid/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 58,
        category: "GND",
        name: "parking chart",
        file: '/charts/grindavik/formicacid/parking.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 59,
        category: "GEN",
        name: "control zone and control area chart",
        file: '/charts/grindavik/formicacid/control zone.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 60,
        category: "SID",
        name: "rnav rwy 06/24 space 1l thacc 1k",
        file: '/charts/grindavik/formicacid/sid space 1l thacc 1k.jpg',
        runways: ["06", "24"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 61,
        category: "SID",
        name: "rnav rwy 06/24 blank 1l 1k youth 1l 1k guess 1l 1k",
        file: '/charts/grindavik/formicacid/sid 1l1 1k.jpg',
        runways: ["06", "24"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 62,
        category: "STAR",
        name: "rnav rwy 24 thacc 1z space 1z",
        file: '/charts/grindavik/formicacid/star 1z.jpg',
        runways: ["24"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 63,
        category: "STAR",
        name: "rnav rwy 06 blank 1t",
        file: '/charts/grindavik/formicacid/star blank 1t.jpg',
        runways: ["06"],
    },   
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 64,
        category: "APP",
        name: "ils/loc rwy 06",
        file: '/charts/grindavik/formicacid/ils loc 06.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 65,
        category: "APP",
        name: "rnp y rwy 06",
        file: '/charts/grindavik/formicacid/rnp y 06.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 66,
        category: "APP",
        name: "rnp z rwy 06",
        file: '/charts/grindavik/formicacid/rnp z 06.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 67,
        category: "APP",
        name: "mls rwy 24",
        file: '/charts/grindavik/formicacid/mls 24.jpg',
        runways: ["24"],
    },
    {
        airport: "IGRV",
        author: "FormicAcid",
        id: 68,
        category: "APP",
        name: "rnp rwy 24",
        file: '/charts/grindavik/formicacid/rnp 24.jpg',
        runways: ["24"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 69,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/paphos/sweet/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 70,
        category: "GND",
        name: "parking chart",
        file: '/charts/paphos/sweet/parking.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 71,
        category: "GEN",
        name: "general information",
        file: '/charts/paphos/sweet/info.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 72,
        category: "GEN",
        name: "aerodrome procedures",
        file: '/charts/paphos/sweet/procedures.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 73,
        category: "SID",
        name: "rnav rwy 17/35 kin 1",
        file: '/charts/paphos/sweet/sid kin 1.jpg',
        runways: ["17", "35"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 74,
        category: "SID",
        name: "rwy 17/35 pfo 1",
        file: '/charts/paphos/sweet/sid pfo 1.jpg',
        runways: ["17", "35"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 75,
        category: "STAR",
        name: "rnav rwy 17/35 jamsi 1",
        file: '/charts/paphos/sweet/star jamsi 1.jpg',
        runways: ["17", "35"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 76,
        category: "STAR",
        name: "rnav rwy 17/35 justy 1",
        file: '/charts/paphos/sweet/star justy 1.jpg',
        runways: ["17", "35"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 75,
        category: "APP",
        name: "ils/loc rwy 17",
        file: '/charts/paphos/sweet/ils loc 17.jpg',
        runways: ["17"],
    },
    {
        airport: "IPAP",
        author: "sweet_kid",
        id: 76,
        category: "APP",
        name: "ils/loc rwy 35",
        file: '/charts/paphos/sweet/ils loc 35.jpg',
        runways: ["35"],
    },
    {
        airport: "TVO",
        author: "FormicAcid",
        id: 77,
        category: "GEN",
        name: "ad 2-69",
        file: '/charts/tavaro/formicacid/ad.jpg',
        runways: [],
    },
    {
        airport: "TVO",
        author: "FormicAcid",
        id: 78,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/tavaro/formicacid/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "TVO",
        author: "FormicAcid",
        id: 79,
        category: "GEN",
        name: "TAVARO",
        file: '/charts/tavaro/formicacid/ctr.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 80,
        category: "GEN",
        name: "aerodrome information",
        file: '/charts/perth/nikryenat/info.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 81,
        category: "GEN",
        name: "airport briefing 1",
        file: '/charts/perth/nikryenat/airport briefing 1.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 82,
        category: "GEN",
        name: "airport briefing 2",
        file: '/charts/perth/nikryenat/airport briefing 2.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 83,
        category: "GEN",
        name: "airport briefing 3",
        file: '/charts/perth/nikryenat/airport briefing 3.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 84,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/perth/nikryenat/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 85,
        category: "SID",
        name: "rnav rwy 11 knife 1a rom 1a camel 1a",
        file: '/charts/perth/nikryenat/sid 1a.jpg',
        runways: ["11"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 86,
        category: "SID",
        name: "rnav rwy 15 knife 1b rom 1b camel 1b",
        file: '/charts/perth/nikryenat/sid 1b.jpg',
        runways: ["15"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 87,
        category: "SID",
        name: "rnav rwy 29 knife 1c rom 1c camel 1c",
        file: '/charts/perth/nikryenat/sid 1c.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 88,
        category: "SID",
        name: "rnav rwy 33 knife 1d rom 1d camel 1d",
        file: '/charts/perth/nikryenat/sid 1d.jpg',
        runways: ["33"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 89,
        category: "STAR",
        name: "rnav rwy 11/15 camel 1w 1x knife 1w 1x rom 1w 1x",
        file: '/charts/perth/nikryenat/star 1w 1x.jpg',
        runways: ["11", "15"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 90,
        category: "STAR",
        name: "rnav rwy 29 camel 1y knife 1y rom 1y",
        file: '/charts/perth/nikryenat/star 1y.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 91,
        category: "STAR",
        name: "rnav rwy 33 camel 1z knife 1z rom 1z",
        file: '/charts/perth/nikryenat/star 1z.jpg',
        runways: ["33"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 92,
        category: "STAR",
        name: "rnav rwy 29 ATC24 A",
        file: '/charts/perth/nikryenat/star atc24.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 93,
        category: "GEN",
        name: "airspace map",
        file: '/charts/perth/nikryenat/airspace map.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 94,
        category: "APP",
        name: "ils/loc x rwy 11",
        file: '/charts/perth/nikryenat/ils loc x 11.jpg',
        runways: ["11"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 95,
        category: "APP",
        name: "ils/loc y rwy 11",
        file: '/charts/perth/nikryenat/ils loc y 11.jpg',
        runways: ["11"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 96,
        category: "APP",
        name: "ils/loc z rwy 11",
        file: '/charts/perth/nikryenat/ils loc z 11.jpg',
        runways: ["11"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 97,
        category: "APP",
        name: "ils/loc y rwy 15",
        file: '/charts/perth/nikryenat/ils loc y 15.jpg',
        runways: ["15"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 98,
        category: "APP",
        name: "ils/loc z rwy 15",
        file: '/charts/perth/nikryenat/ils loc z 15.jpg',
        runways: ["15"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 99,
        category: "APP",
        name: "rnp rwy 29",
        file: '/charts/perth/nikryenat/rnp 29.jpg',
        runways: ["29"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 100,
        category: "APP",
        name: "rnp rwy 33",
        file: '/charts/perth/nikryenat/rnp 33.jpg',
        runways: ["33"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 101,
        category: "APP",
        name: "circling rwy 29",
        file: '/charts/perth/nikryenat/circle 29.jpg',
        runways: ["29"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 102,
        category: "APP",
        name: "circling rwy 33",
        file: '/charts/perth/nikryenat/circle 33.jpg',
        runways: ["33"],
    },  
    {
        airport: "IPPH",
        author: "Nikita39Gamer, Natto, Ryseaviation",
        id: 103,
        category: "APP",
        name: "loc dme rwy 29",
        file: '/charts/perth/nikryenat/loc dme 29.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 104,
        category: "GND",
        name: "a225 ground movement",
        file: '/charts/perth/aeronav/a225.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 105,
        category: "GND",
        name: "a380 b747 ground movement",
        file: '/charts/perth/aeronav/a380 b747.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 106,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/perth/aeronav/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 107,
        category: "GND",
        name: "parking chart",
        file: '/charts/perth/aeronav/parking.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 108,
        category: "GEN",
        name: "aerodrome information",
        file: '/charts/perth/aeronav/info.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 115,
        category: "GEN",
        name: "aerodrome procedures",
        file: '/charts/perth/aeronav/procedures.jpg',
        runways: [],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 109,
        category: "SID",
        name: "rwy 11/15/29/33 per 1",
        file: '/charts/perth/aeronav/sid per 1.jpg',
        runways: ["11", "15", "29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 110,
        category: "SID",
        name: "rnav rwy 11/29/33 diner 1",
        file: '/charts/perth/aeronav/sid diner 1.jpg',
        runways: ["11", "29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 111,
        category: "SID",
        name: "rnav rwy 11/29/33 camel 1",
        file: '/charts/perth/aeronav/sid camel 1.jpg',
        runways: ["11", "29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 112,
        category: "STAR",
        name: "rwy 29/33 honda 1",
        file: '/charts/perth/aeronav/star honda 1.jpg',
        runways: ["29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 113,
        category: "STAR",
        name: "rwy 11/15/29/33 sista 1",
        file: '/charts/perth/aeronav/star sista 1.jpg',
        runways: ["11", "15", "29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 114,
        category: "STAR",
        name: "rwy 11/15/29/33 talis 1",
        file: '/charts/perth/aeronav/star talis 1.jpg',
        runways: ["11", "15", "29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 116,
        category: "APP",
        name: "ils/loc rwy 11",
        file: '/charts/perth/aeronav/ils loc 11.jpg',
        runways: ["11"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 117,
        category: "APP",
        name: "rnp z rwy 29",
        file: '/charts/perth/aeronav/rnp z 29.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 118,
        category: "APP",
        name: "lda y rwy 29",
        file: '/charts/perth/aeronav/lda y 29.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 119,
        category: "APP",
        name: "lda z rwy 29",
        file: '/charts/perth/aeronav/lda z 29.jpg',
        runways: ["29"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 120,
        category: "APP",
        name: "gls rwy 33",
        file: '/charts/perth/aeronav/gls 33.jpg',
        runways: ["33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 121,
        category: "APP",
        name: "haven island visual rwy 29/33",
        file: '/charts/perth/aeronav/island visual 29 33.jpg',
        runways: ["29", "33"],
    },
    {
        airport: "IPPH",
        author: "AeroNav",
        id: 122,
        category: "APP",
        name: "haven stacks visual rwy 29/33",
        file: '/charts/perth/aeronav/stacks visual 29 33.jpg',
        runways: ["29", "33"],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 123,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/mcconnell/aeronav/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 124,
        category: "GEN",
        name: "aerodrome information",
        file: '/charts/mcconnell/aeronav/info.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 125,
        category: "SID",
        name: "rwy 09L/09R/27L/27R IAB 1",
        file: '/charts/mcconnell/aeronav/sid iab 1.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 126,
        category: "STAR",
        name: "rwy 09L/09R/27L/27R lck 1",
        file: '/charts/mcconnell/aeronav/star lck 1.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 127,
        category: "APP",
        name: "ILS/LOC RWY 09L",
        file: '/charts/mcconnell/aeronav/ils loc 09l.jpg',
        runways: ["09L"],
    },
    {
        airport: "IIAB",
        author: "AeroNav",
        id: 128,
        category: "APP",
        name: "ILS/LOC RWY 27R",
        file: '/charts/mcconnell/aeronav/ils loc 27r.jpg',
        runways: ["27R"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 129,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/mcconnell/p1anes/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 130,
        category: "GEN",
        name: "airport briefing 1",
        file: '/charts/mcconnell/p1anes/brief 1.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 131,
        category: "GEN",
        name: "airport briefing 2",
        file: '/charts/mcconnell/p1anes/brief 2.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 132,
        category: "GEN",
        name: "airport briefing 3",
        file: '/charts/mcconnell/p1anes/brief 3.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 133,
        category: "GEN",
        name: "control zone and control area chart",
        file: '/charts/mcconnell/p1anes/control zone.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 134,
        category: "SID",
        name: "rnav rwy 09l/r candle 1",
        file: '/charts/mcconnell/p1anes/sid candle 1.jpg',
        runways: ["09"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 135,
        category: "SID",
        name: "rnav rwy 27l/r candle 2",
        file: '/charts/mcconnell/p1anes/sid candle 2.jpg',
        runways: ["27"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 136,
        category: "STAR",
        name: "rnav rwy 09l/r rents 3a",
        file: '/charts/mcconnell/p1anes/star rents 3a.jpg',
        runways: ["09"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 137,
        category: "STAR",
        name: "rnav rwy 09l/r asp 3a",
        file: '/charts/mcconnell/p1anes/star asp 3a.jpg',
        runways: ["09"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 138,
        category: "STAR",
        name: "rnav rwy 27l/r asp 4a",
        file: '/charts/mcconnell/p1anes/star asp 4a.jpg',
        runways: ["27"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 139,
        category: "STAR",
        name: "rnav rwy 27l/r rents 4a",
        file: '/charts/mcconnell/p1anes/star rents 4a.jpg',
        runways: ["27"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 140,
        category: "STAR",
        name: "rnav rwy 26l/r debug 4a",
        file: '/charts/mcconnell/p1anes/star debug 4a.jpg',
        runways: ["27"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 141,
        category: "APP",
        name: "ils rwy 09l",
        file: '/charts/mcconnell/p1anes/ils 09l.jpg',
        runways: ["09L"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 142,
        category: "APP",
        name: "ils rwy 09r",
        file: '/charts/mcconnell/p1anes/ils 09r.jpg',
        runways: ["09R"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 143,
        category: "APP",
        name: "lda rwy 27l",
        file: '/charts/mcconnell/p1anes/lda 27l.jpg',
        runways: ["27L"],
    },
    {
        airport: "IIAB",
        author: "p1anes",
        id: 144,
        category: "APP",
        name: "lda rwy 27r",
        file: '/charts/mcconnell/p1anes/lda 27r.jpg',
        runways: ["27R"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 145,
        category: "GEN",
        name: "aerodrome procedures",
        file: '/charts/mcconnell/ezy/procs.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 146,
        category: "GND",
        name: "ground movement chart",
        file: '/charts/mcconnell/ezy/taxi.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 147,
        category: "GND",
        name: "parking chart",
        file: '/charts/mcconnell/ezy/ramp.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 148,
        category: "GEN",
        name: "mcconnell",
        file: '/charts/mcconnell/ezy/ctz.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 149,
        category: "SID",
        name: "sid rwy 09L/09r/27l/27r",
        file: '/charts/mcconnell/ezy/sid.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 150,
        category: "STAR",
        name: "star rwy 09L/09r/27l/27r",
        file: '/charts/mcconnell/ezy/star.jpg',
        runways: [],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 151,
        category: "APP",
        name: "ILS/LOC DME RWY 09L",
        file: '/charts/mcconnell/ezy/ils loc dme 09l.jpg',
        runways: ["09L"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 152,
        category: "APP",
        name: "ILS/LOC DME RWY 09R",
        file: '/charts/mcconnell/ezy/ils loc dme 09r.jpg',
        runways: ["09R"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 153,
        category: "APP",
        name: "ILS/LOC DME RWY 27L",
        file: '/charts/mcconnell/ezy/ils loc dme 27l.jpg',
        runways: ["27L"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 154,
        category: "APP",
        name: "ILS/LOC DME RWY 27R",
        file: '/charts/mcconnell/ezy/ils loc dme 27r.jpg',
        runways: ["27R"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 155,
        category: "APP",
        name: "SRA RWY 27R",
        file: '/charts/mcconnell/ezy/sra 27r.jpg',
        runways: ["27R"],
    },
    {
        airport: "IIAB",
        author: "EzyDubbs",
        id: 156,
        category: "APP",
        name: "ILS/LOC DME RWY 27R",
        file: '/charts/mcconnell/ezy/ils loc dme 27r.jpg',
        runways: ["27R"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 157,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/larnaca/aloha/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 158,
        category: "GND",
        name: "parking chart",
        file: '/charts/larnaca/aloha/parking.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 159,
        category: "GEN",
        name: "aerodrome information",
        file: '/charts/larnaca/aloha/info.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 160,
        category: "GEN",
        name: "airport briefing",
        file: '/charts/larnaca/aloha/brief.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 161,
        category: "GEN",
        name: "radar minimum altitudes",
        file: '/charts/larnaca/aloha/radar min alt.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 162,
        category: "SID",
        name: "rnav rwy 06 lazer 2s lambo 2s monti 2s",
        file: '/charts/larnaca/aloha/sid 2s.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 163,
        category: "SID",
        name: "rnav rwy 24 lazer 2y lambo 2y monti 2y",
        file: '/charts/larnaca/aloha/sid 2y.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 164,
        category: "SID",
        name: "rwy 06/24 ilar 1q 1m",
        file: '/charts/larnaca/aloha/sid ilar.jpg',
        runways: ["06", "24"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 165,
        category: "STAR",
        name: "rnav rwy 06 elsas 2h grass 2h rents 2h",
        file: '/charts/larnaca/aloha/star 2h.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 166,
        category: "STAR",
        name: "rnav rwy 24 elsas 2g grass 2g rents 2g",
        file: '/charts/larnaca/aloha/star 2g.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 167,
        category: "APP",
        name: "ils/loc rwy 06",
        file: '/charts/larnaca/aloha/ils loc 06.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 168,
        category: "APP",
        name: "circling vor dme rwy 24 initial",
        file: '/charts/larnaca/aloha/circling vordme 24.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 169,
        category: "APP",
        name: "circling vor dme rwy 24",
        file: '/charts/larnaca/aloha/circling vordme 24 visual.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Aloha516",
        id: 170,
        category: "APP",
        name: "circling vor dme rwy 24 missed",
        file: '/charts/larnaca/aloha/circling vordme 24 missed.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 171,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/larnaca/nikita39_ryse/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 172,
        category: "GND",
        name: "Terminal area chart",
        file: '/charts/larnaca/nikita39_ryse/tma.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 173,
        category: "STAR",
        name: "RNAV RWY 06 REAPR 1K ANYMS 1K JAMSI 1K JUSTY 1K",
        file: '/charts/larnaca/nikita39_ryse/star 1k.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 174,
        category: "STAR",
        name: "RNAV RWY 24 REAPR 1m ANYMS 1m JAMSI 1m JUSTY 1m",
        file: '/charts/larnaca/nikita39_ryse/star 1m.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 175,
        category: "SID",
        name: "RNAV RWY 24 REAPR 1l ANYMS 1l JAMSI 1l JUSTY 1l",
        file: '/charts/larnaca/nikita39_ryse/sid 1l.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 176,
        category: "SID",
        name: "RNAV RWY 06 REAPR 1j ANYMS 1j JAMSI 1j JUSTY 1j",
        file: '/charts/larnaca/nikita39_ryse/sid 1j.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 177,
        category: "APP",
        name: "ILS/LOC RWY 06",
        file: '/charts/larnaca/nikita39_ryse/ils loc 06.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 178,
        category: "APP",
        name: "CIRCLING RWY 24 INITIAL",
        file: '/charts/larnaca/nikita39_ryse/circling 06 init.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "Nikita39Gamer, ryseaviation",
        id: 179,
        category: "APP",
        name: "CIRCLING RWY 24",
        file: '/charts/larnaca/nikita39_ryse/circling 06.jpg',
        runways: ["24"],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 180,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/sauth/aloha/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 181,
        category: "GND",
        name: "aerodrome information",
        file: '/charts/sauth/aloha/info.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 182,
        category: "SID",
        name: "rnav rwy 08/26 seeks 1c 2c",
        file: '/charts/sauth/aloha/sid 1.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 183,
        category: "SID",
        name: "rnav rwy 08/26 packt 2c barnie 1c",
        file: '/charts/sauth/aloha/sid 2.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 184,
        category: "SID",
        name: "rnav rwy 08/26 shrek 1c 2c",
        file: '/charts/sauth/aloha/sid 3.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 185,
        category: "SID",
        name: "rnav rwy 08/26 dackd 1c 2c",
        file: '/charts/sauth/aloha/sid 4.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 186,
        category: "SID",
        name: "rnav rwy 08/26 hacke 1c 2c",
        file: '/charts/sauth/aloha/sid 5.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 187,
        category: "STAR",
        name: "rnav rwy 08 space 1b shrek 1b dackd 1b hacke 1b",
        file: '/charts/sauth/aloha/star 1b.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 188,
        category: "STAR",
        name: "rnav rwy 08 packt 1b waste 1b",
        file: '/charts/sauth/aloha/star 1b 2.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 189,
        category: "STAR",
        name: "rnav rwy 26 space 2b dackd 2b hecks 2b",
        file: '/charts/sauth/aloha/star 2b 2.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 190,
        category: "STAR",
        name: "rnav rwy 26 alder 2b hoggs 2b stack 2b",
        file: '/charts/sauth/aloha/star 2b.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Aloha516",
        id: 191,
        category: "APP",
        name: "ils y rwy 26",
        file: '/charts/sauth/aloha/ils y 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 192,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/sauth/nikita39_ryse/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 193,
        category: "GEN",
        name: "airport briefing 1",
        file: '/charts/sauth/nikita39_ryse/brief 1.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 194,
        category: "GEN",
        name: "airport briefing 2",
        file: '/charts/sauth/nikita39_ryse/brief 2.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 195,
        category: "GEN",
        name: "airport briefing 3",
        file: '/charts/sauth/nikita39_ryse/brief 3.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 196,
        category: "SID",
        name: "rwy 08 shrek 1k space 1k beans 1k alder 1k",
        file: '/charts/sauth/nikita39_ryse/sid 1k.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 197,
        category: "SID",
        name: "rnav rwy 08 shrek 1j space 1j beans 1j alder 1j",
        file: '/charts/sauth/nikita39_ryse/sid 1j.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 196,
        category: "SID",
        name: "rwy 26 shrek 1l space 1l beans 1l alder 1l",
        file: '/charts/sauth/nikita39_ryse/sid 1l.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 197,
        category: "SID",
        name: "rnav rwy 26 shrek 1m space 1m beans 1m alder 1m",
        file: '/charts/sauth/nikita39_ryse/sid 1m.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 198,
        category: "GEN",
        name: "terminal area chat",
        file: '/charts/sauth/nikita39_ryse/tma.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 199,
        category: "STAR",
        name: "rnav rwy 08 shrek 1s space 1s beans 1s alder 1s",
        file: '/charts/sauth/nikita39_ryse/star 1s.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 200,
        category: "STAR",
        name: "rnav rwy 26 shrek 1t space 1t beans 1t alder 1t",
        file: '/charts/sauth/nikita39_ryse/star 1t.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 201,
        category: "STAR",
        name: "rnav rwy 08/26 shrek 1r space 1r beans 1r alder 1r",
        file: '/charts/sauth/nikita39_ryse/star 1r.jpg',
        runways: ["08", "26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 202,
        category: "APP",
        name: "LOC RWY 08",
        file: '/charts/sauth/nikita39_ryse/loc 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 203,
        category: "APP",
        name: "ILS/LOC RWY 26",
        file: '/charts/sauth/nikita39_ryse/ils loc 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 204,
        category: "APP",
        name: "rnp RWY 08",
        file: '/charts/sauth/nikita39_ryse/rnp 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "Nikita39Gamer, ryseaviation",
        id: 205,
        category: "APP",
        name: "rnp RWY 26",
        file: '/charts/sauth/nikita39_ryse/rnp 26.jpg',
        runways: ["26"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 206,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/izol/sander/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 207,
        category: "GEN",
        name: "ad 1",
        file: '/charts/izol/sander/ad 1.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 208,
        category: "GEN",
        name: "ad 2",
        file: '/charts/izol/sander/ad 2.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 209,
        category: "GEN",
        name: "ad 3",
        file: '/charts/izol/sander/ad 3.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 210,
        category: "SID",
        name: "rnav rwy 10 chain 5a dunks 5a justy 5a udmug 5a",
        file: '/charts/izol/sander/sid 5a.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 211,
        category: "SID",
        name: "rnav rwy 28 anyms 5b dunks 5b cyril 5b",
        file: '/charts/izol/sander/sid 5b.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 212,
        category: "STAR",
        name: "rnav rwy 28 camel 1d udmug 1d",
        file: '/charts/izol/sander/star 1d.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 213,
        category: "STAR",
        name: "rnav rwy 28 chain 2d doggo 2d justy 2d",
        file: '/charts/izol/sander/star 2d.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 214,
        category: "APP",
        name: "rnp x rwy 10",
        file: '/charts/izol/sander/rnp x 10.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "Sanderli25",
        id: 215,
        category: "APP",
        name: "visual approach chart",
        file: '/charts/izol/sander/vac.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 216,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/izol/ryse/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 217,
        category: "GEN",
        name: "aerodrome information",
        file: '/charts/izol/ryse/info.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 218,
        category: "GEN",
        name: "terminal area chart",
        file: '/charts/izol/ryse/tma.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 219,
        category: "GEN",
        name: "radar minimum altitudes",
        file: '/charts/izol/ryse/radar min alt.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 220,
        category: "SID",
        name: "rnav rwy 10 del 1l dunks 1l silva 1l",
        file: '/charts/izol/ryse/sid 1l.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 221,
        category: "SID",
        name: "rnav rwy 28 del 1j dunks 1j silva 1j",
        file: '/charts/izol/ryse/sid 1j.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 222,
        category: "STAR",
        name: "rnav rwy 10 del 1h dunks 1h silva 1h",
        file: '/charts/izol/ryse/star 1h.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 223,
        category: "STAR",
        name: "rnav rwy 28 del 1k dunks 1k silva 1k",
        file: '/charts/izol/ryse/star 1k.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 224,
        category: "APP",
        name: "ils/loc rwy 10",
        file: '/charts/izol/ryse/ils loc 10.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "ryseaviation",
        id: 225,
        category: "APP",
        name: "ils/loc rwy 28",
        file: '/charts/izol/ryse/ils loc 28.jpg',
        runways: ["28"],
    },
    {
        airport: "IBAR",
        author: "ryseaviation",
        id: 226,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barra/ryse/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IBAR",
        author: "ryseaviation",
        id: 227,
        category: "SID",
        name: "rnav sid",
        file: '/charts/barra/ryse/sid.jpg',
        runways: [],
    },
    {
        airport: "IBAR",
        author: "ryseaviation",
        id: 228,
        category: "STAR",
        name: "rnav star",
        file: '/charts/barra/ryse/star.jpg',
        runways: [],
    },
    {
        airport: "IBAR",
        author: "ryseaviation",
        id: 229,
        category: "APP",
        name: "ils/loc sand",
        file: '/charts/barra/ryse/ils.jpg',
        runways: [],
    },
    {
        airport: "IBAR",
        author: "aerosd",
        id: 230,
        category: "GEN",
        name: "barra",
        file: '/charts/barra/aerosd/info.jpg',
        runways: [],
    },
    {
        airport: "IBAR",
        author: "aerosd",
        id: 231,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barra/aerosd/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "p1anes",
        id: 232,
        category: "GEN",
        name: "control area chart",
        file: '/charts/grindavik/p1anes/control area.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 233,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/grindavik/aeronav/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 234,
        category: "GND",
        name: "parking chart",
        file: '/charts/grindavik/aeronav/parking.jpg',
        runways: [],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 235,
        category: "SID",
        name: "rnav rwy 06 youth 3",
        file: '/charts/grindavik/aeronav/sid youth 3.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 236,
        category: "SID",
        name: "rnav rwy 06 hawkn 1",
        file: '/charts/grindavik/aeronav/sid hawkn 1.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 237,
        category: "SID",
        name: "rnav rwy 24 celar 3",
        file: '/charts/grindavik/aeronav/sid celar 3.jpg',
        runways: ["24"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 238,
        category: "SID",
        name: "rnav rwy 24 thenr 3",
        file: '/charts/grindavik/aeronav/sid thenr 3.jpg',
        runways: ["24"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 239,
        category: "SID",
        name: "rwy 06/24 gvk 1",
        file: '/charts/grindavik/aeronav/sid gvk 1.jpg',
        runways: ["06", "24"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 240,
        category: "STAR",
        name: "rnav rwy 06 goldn 1",
        file: '/charts/grindavik/aeronav/star goldn 1.jpg',
        runways: ["06",],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 241,
        category: "STAR",
        name: "rnav rwy 06/24 space 1",
        file: '/charts/grindavik/aeronav/star space 1.jpg',
        runways: ["06", "24"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 242,
        category: "APP",
        name: "rnp rwy 06",
        file: '/charts/grindavik/aeronav/rnp 06.jpg',
        runways: ["06"],
    },
    {
        airport: "IGRV",
        author: "AeroNav",
        id: 243,
        category: "APP",
        name: "rnp rwy 24",
        file: '/charts/grindavik/aeronav/rnp 24.jpg',
        runways: ["24"],
    },
    {
        airport: "IHEN",
        author: "StasON_Toppp",
        id: 244,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/henstridge/stason/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IHEN",
        author: "StasON_Toppp",
        id: 245,
        category: "SID",
        name: "rnav rwy 17 foria 1a aqwrt 1a",
        file: '/charts/henstridge/stason/sid 1a.jpg',
        runways: ["17"],
    },
    {
        airport: "IHEN",
        author: "StasON_Toppp",
        id: 246,
        category: "SID",
        name: "rnav rwy 35 foria 1b aqwrt 1b",
        file: '/charts/henstridge/stason/sid 1b.jpg',
        runways: ["35"],
    },
    {
        airport: "IHEN",
        author: "StasON_Toppp",
        id: 247,
        category: "STAR",
        name: "rnav rwy 17 foria 2a aqwrt 2a",
        file: '/charts/henstridge/stason/star 2b 2.jpg',
        runways: ["17"],
    },
    {
        airport: "IHEN",
        author: "StasON_Toppp",
        id: 248,
        category: "STAR",
        name: "rnav rwy 35 foria 2b aqwrt 2b",
        file: '/charts/henstridge/stason/star 2b.jpg',
        runways: ["35"],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 249,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/izol/midwest/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 250,
        category: "GEN",
        name: "airspace map",
        file: '/charts/izol/midwest/airspace.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 251,
        category: "GEN",
        name: "MSA Chart",
        file: '/charts/izol/midwest/msa.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 252,
        category: "SID",
        name: "rwy 10/28 sista 1a talis 1a camel 1a silva 1a justy 1a",
        file: '/charts/izol/midwest/sid 1a.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 253,
        category: "SID",
        name: "rnav rwy 10/28 silva 1b justy 1b camel 1b",
        file: '/charts/izol/midwest/sid 1b.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 254,
        category: "STAR",
        name: "rwy 10/28 btm 2b org 2b rom 2b",
        file: '/charts/izol/midwest/star 2b.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 255,
        category: "STAR",
        name: "rwy 10/28 vox 1b tes 1b del 1b det 1",
        file: '/charts/izol/midwest/star 1b.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 256,
        category: "STAR",
        name: "rnav rwy 10/28 sista 3a camel 3a",
        file: '/charts/izol/midwest/star 3a.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 257,
        category: "STAR",
        name: "rnav rwy 10/28 oceen 3b justy 3b",
        file: '/charts/izol/midwest/star 3b.jpg',
        runways: [],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 258,
        category: "APP",
        name: "lda rwy 10",
        file: '/charts/izol/midwest/lda 10.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 259,
        category: "APP",
        name: "North rnav rwy 10",
        file: '/charts/izol/midwest/n rnav 10.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 260,
        category: "APP",
        name: "south rnav rwy 10",
        file: '/charts/izol/midwest/s rnav 10.jpg',
        runways: ["10"],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 261,
        category: "APP",
        name: "ils/loc rwy 28",
        file: '/charts/izol/midwest/ils loc 28.jpg',
        runways: ["28"],
    },
    {
        airport: "IZOL",
        author: "Midwest Avgeek",
        id: 262,
        category: "APP",
        name: "rnav rwy 28",
        file: '/charts/izol/midwest/rnav 28.jpg',
        runways: ["28"],
    },
    {
        airport: "ILAR",
        author: "makiwasmyidea",
        id: 263,
        category: "SID",
        name: "rnav rwy 06 can 1a lazer 1a rents 1b jacki 1b",
        file: '/charts/larnaca/maki/sid.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "greek_dutchman",
        id: 264,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/larnaca/dutchman/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ILAR",
        author: "greek_dutchman",
        id: 265,
        category: "SID",
        name: "rnav rwy 06 justy 2g jamsi 2g lazer 2g anyms 2g",
        file: '/charts/larnaca/dutchman/sid 2g.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "greek_dutchman",
        id: 266,
        category: "SID",
        name: "rnav rwy 24 justy 2h jamsi 2h lazer 2h anyms 2h",
        file: '/charts/larnaca/dutchman/sid 2h.jpg',
        runways: ["24"],
    },
    {
        airport: "ILAR",
        author: "greek_dutchman",
        id: 267,
        category: "STAR",
        name: "rnav rwy 06 justy 2c anyms 2c jamsi 2c lazer 2c saves 2c reapr 2c",
        file: '/charts/larnaca/dutchman/star 2c.jpg',
        runways: ["06"],
    },
    {
        airport: "ILAR",
        author: "greek_dutchman",
        id: 268,
        category: "STAR",
        name: "rnav rwy 24 justy 2d anyms 2d jamsi 2d saves 2d",
        file: '/charts/larnaca/dutchman/star 2d.jpg',
        runways: ["24"],
    },
    {
        airport: "ILKL",
        author: "EkayDuhh & Kita",
        id: 269,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/lukla/ekd/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ILKL",
        author: "EkayDuhh & Kita",
        id: 270,
        category: "GEN",
        name: "airport briefing",
        file: '/charts/lukla/ekd/brief.jpg',
        runways: [],
    },
    {
        airport: "ILKL",
        author: "EkayDuhh & Kita",
        id: 271,
        category: "SID",
        name: "rnav rwy 09 wells 1a noonu 1a kella 1a sista 1a talis 1a strax 1a tindr 1a",
        file: '/charts/lukla/ekd/sid.jpg',
        runways: ["09"],
    },
    {
        airport: "ILKL",
        author: "EkayDuhh & Kita",
        id: 272,
        category: "STAR",
        name: "rnav rwy 27 strax 2a kella 2a noonu 2a",
        file: '/charts/lukla/ekd/star.jpg',
        runways: ["27"],
    },
    {
        airport: "IPAP",
        author: "playevator",
        id: 273,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/paphos/playevator/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "playevator",
        id: 274,
        category: "SID",
        name: "rnav rwy 17 rents 2a",
        file: '/charts/paphos/playevator/sid rents 2a.jpg',
        runways: ["17"],
    },
    {
        airport: "IPAP",
        author: "playevator",
        id: 275,
        category: "SID",
        name: "rnav rwy 35 rents 1a",
        file: '/charts/paphos/playevator/sid rents 1a.jpg',
        runways: ["35"],
    },
    {
        airport: "IPAP",
        author: "playevator",
        id: 276,
        category: "STAR",
        name: "rnav rwy 17 rents 1b doggo 1b jamsi 1b",
        file: '/charts/paphos/playevator/sid rents 1b.jpg',
        runways: ["17"],
    },
    {
        airport: "IPAP",
        author: "playevator",
        id: 277,
        category: "STAR",
        name: "rnav rwy 35 rents 2b doggo 2b jamsi 2b",
        file: '/charts/paphos/playevator/sid rents 2b.jpg',
        runways: ["35"],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 278,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/paphos/sander/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 279,
        category: "GEN",
        name: "paphos 1",
        file: '/charts/paphos/sander/info.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 280,
        category: "GEN",
        name: "paphos 2",
        file: '/charts/paphos/sander/info 2.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 281,
        category: "SID",
        name: "rnav rwy 17/35 rents 1a 1b",
        file: '/charts/paphos/sander/sid.jpg',
        runways: [],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 282,
        category: "APP",
        name: "ils/loc rwy 17",
        file: '/charts/paphos/sander/ils loc 17.jpg',
        runways: ["17"],
    },
    {
        airport: "IPAP",
        author: "Sanderli25",
        id: 283,
        category: "APP",
        name: "ils/loc rwy 35",
        file: '/charts/paphos/sander/ils loc 35.jpg',
        runways: ["35"],
    },
    {
        airport: "IDCS",
        author: "MrGearz",
        id: 284,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/saba/gearz/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IDCS",
        author: "MrGearz",
        id: 285,
        category: "SID",
        name: "rnav rwy 07/25 bully 1a piper 1a 1b",
        file: '/charts/saba/gearz/sid.jpg',
        runways: [],
    },
    {
        airport: "IDCS",
        author: "MrGearz",
        id: 286,
        category: "STAR",
        name: "rnav rwy 07 bully 1b guleg 1a",
        file: '/charts/saba/gearz/star 07.jpg',
        runways: ["07"],
    },
    {
        airport: "IDCS",
        author: "MrGearz",
        id: 287,
        category: "STAR",
        name: "rnav rwy 25 knife 1a tinder 1a",
        file: '/charts/saba/gearz/star 25.jpg',
        runways: ["25"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 288,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/najaf/midwest/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 289,
        category: "GEN",
        name: "airspace map",
        file: '/charts/najaf/midwest/airspace.jpg',
        runways: [],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 290,
        category: "GEN",
        name: "minimum sector altitude",
        file: '/charts/najaf/midwest/msa.jpg',
        runways: [],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 291,
        category: "SID",
        name: "rnav rwy 07/25 dunks 2k sista 2k",
        file: '/charts/najaf/midwest/sid.jpg',
        runways: [],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 292,
        category: "STAR",
        name: "rnav rwy 07 anyms 2b detox 2b",
        file: '/charts/najaf/midwest/star 07 1.jpg',
        runways: ["07"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 293,
        category: "STAR",
        name: "rnav rwy 07 camel 1a noonu 1a silva 1a",
        file: '/charts/najaf/midwest/star 07 2.jpg',
        runways: ["07"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 294,
        category: "STAR",
        name: "rnav rwy 25 cyril 3c camel 3c noonu 3c",
        file: '/charts/najaf/midwest/star 25.jpg',
        runways: ["25"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 295,
        category: "APP",
        name: "ils/loc rwy 25",
        file: '/charts/najaf/midwest/ils loc 25.jpg',
        runways: ["25"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 296,
        category: "APP",
        name: "vor dme rwy 25",
        file: '/charts/najaf/midwest/vordme 25.jpg',
        runways: ["25"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 297,
        category: "APP",
        name: "rnav (rnp) y 07",
        file: '/charts/najaf/midwest/rnp y 07.jpg',
        runways: ["07"],
    },
    {
        airport: "IJAF",
        author: "Midwest Avgeek",
        id: 298,
        category: "APP",
        name: "rnav (rnp) z 07",
        file: '/charts/najaf/midwest/rnp z 07.jpg',
        runways: ["07"],
    },
    {
        airport: "IBTH",
        author: "EkayDuhhh",
        id: 299,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barthelemy/ekay/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "EkayDuhhh",
        id: 300,
        category: "SID",
        name: "rnav rwy 09 camel 1c rm 1f diner 1g",
        file: '/charts/barthelemy/ekay/sid 09.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "EkayDuhhh",
        id: 301,
        category: "SID",
        name: "rnav rwy 27 oceen 1g probe 1s welsh 1r",
        file: '/charts/barthelemy/ekay/sid 27.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "EkayDuhhh",
        id: 302,
        category: "STAR",
        name: "rnav rwy 09 gavin 1o probe 1a welsh 1a",
        file: '/charts/barthelemy/ekay/star 09.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "EkayDuhhh",
        id: 303,
        category: "STAR",
        name: "rnav rwy 27 diner 1a camel 1a",
        file: '/charts/barthelemy/ekay/star 27.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 304,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/barthelemy/playevator/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 305,
        category: "SID",
        name: "rnav rwy 09 probe 1f rom 1f camel 1f",
        file: '/charts/barthelemy/playevator/sid 09 1.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 306,
        category: "SID",
        name: "rnav rwy 09 index 1g oceen 1g",
        file: '/charts/barthelemy/playevator/sid 09 2.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 307,
        category: "SID",
        name: "rnav rwy 27 probe 1h welsh 1h silva 1h",
        file: '/charts/barthelemy/playevator/sid 27.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 308,
        category: "STAR",
        name: "rnav rwy 09 silva 1i oceen 1i welsh 1i diner 1i rendr 1i",
        file: '/charts/barthelemy/playevator/star 09.jpg',
        runways: ["09"],
    },
    {
        airport: "IBTH",
        author: "playevator",
        id: 309,
        category: "STAR",
        name: "rnav rwy 27 probe 1j camel 1j silva 1j",
        file: '/charts/barthelemy/playevator/star 27.jpg',
        runways: ["27"],
    },
    {
        airport: "IBTH",
        author: "Sanderli25",
        id: 310,
        category: "GND",
        name: "ad 2 aerodrome chart",
        file: '/charts/barthelemy/sander/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "IBTH",
        author: "Sanderli25",
        id: 311,
        category: "GEN",
        name: "ad 2 app 01 att 01",
        file: '/charts/barthelemy/sander/ad 2 app 01 att 01.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "AeroSD",
        id: 312,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/sauth/aerosd/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "AeroSD",
        id: 313,
        category: "GND",
        name: "aerodrome parking/docking chart",
        file: '/charts/sauth/aerosd/parking.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "AeroSD",
        id: 314,
        category: "GEN",
        name: "sauthemptona",
        file: '/charts/sauth/aerosd/info.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 315,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/sauth/pluton/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 316,
        category: "GEN",
        name: "vfr chart",
        file: '/charts/sauth/pluton/vfr.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 317,
        category: "SID",
        name: "rnav rwy 08 shrek 1d space 1d",
        file: '/charts/sauth/pluton/sid 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 318,
        category: "SID",
        name: "rnav rwy 26 shrek 1l space 1l",
        file: '/charts/sauth/pluton/sid 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 319,
        category: "SID",
        name: "rnav rwy 08/26 alder 1l 1d robux 1l 1d",
        file: '/charts/sauth/pluton/sid.jpg',
        runways: ["08", "26"],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 320,
        category: "STAR",
        name: "rnav rwy 08/26 alder bl 1n robux bl 1n",
        file: '/charts/sauth/pluton/star 1.jpg',
        runways: ["08", "26"],
    },
    {
        airport: "ISAU",
        author: "PlutonFordo",
        id: 321,
        category: "STAR",
        name: "rnav rwy 08/26 shrek bl 1n space bl 1n",
        file: '/charts/sauth/pluton/star 2.jpg',
        runways: ["08", "26"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 322,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/sauth/737/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 323,
        category: "GEN",
        name: "airspace chart",
        file: '/charts/sauth/737/airspace.jpg',
        runways: [],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 324,
        category: "SID",
        name: "rnav rwy 08 shrek 2o space 2o seeks 2o alder 2o",
        file: '/charts/sauth/737/sid 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 325,
        category: "SID",
        name: "rnav rwy 26 shrek 2k space 2k seeks 2k alder 2k",
        file: '/charts/sauth/737/sid 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 326,
        category: "STAR",
        name: "rnav rwy 08 shrek 2m space 2m seeks 2m alder 2m",
        file: '/charts/sauth/737/star 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 327,
        category: "STAR",
        name: "rnav rwy 26 shrek 2p space 2p seeks 2p alder 2p",
        file: '/charts/sauth/737/star 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 328,
        category: "APP",
        name: "ils/loc rwy 08",
        file: '/charts/sauth/737/ils 08.jpg',
        runways: ["08"],
    },
    {
        airport: "ISAU",
        author: "SevenThirtySeven",
        id: 329,
        category: "APP",
        name: "ils/loc rwy 26",
        file: '/charts/sauth/737/ils 26.jpg',
        runways: ["26"],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 330,
        category: "GND",
        name: "aerodrome chart",
        file: '/charts/skopelos/alisoe/aerodrome.jpg',
        runways: [],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 331,
        category: "GEN",
        name: "aerodrome obstacle chart",
        file: '/charts/skopelos/alisoe/obstacle.jpg',
        runways: [],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 332,
        category: "SID",
        name: "rnav rwy 05 oceen 1v cawze 1v del 1v clr 1v anyms 1v",
        file: '/charts/skopelos/alisoe/sid 05.jpg',
        runways: ["05"],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 333,
        category: "SID",
        name: "rnav rwy 23 oceen 1l cawze 1l del 1l clr 1l anyms 1l",
        file: '/charts/skopelos/alisoe/sid 23.jpg',
        runways: ["23"],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 334,
        category: "STAR",
        name: "rnav rwy 05 oceen 2t cawze 2t del 2t anyms 2t",
        file: '/charts/skopelos/alisoe/star 05.jpg',
        runways: ["05"],
    },
    {
        airport: "ISKP",
        author: "Alisoe",
        id: 335,
        category: "STAR",
        name: "rnav rwy 23 oceen 2e cawze 2e del 2e anyms 2e",
        file: '/charts/skopelos/alisoe/star 23.jpg',
        runways: ["23"],
    },
    {
        airport: "ITKO",
        author: "SQD_Yeet",
        id: 336,
        category: "SID",
        name: "rnav rwy 02 piper 1a onder 1a",
        file: '/charts/tokyo/sqd/sid.jpg',
        runways: ["02"],
    },
    {
        airport: "ITKO",
        author: "SQD_Yeet",
        id: 337,
        category: "STAR",
        name: "rnav rwy 13/20/31 RENDR 1A KNIFe 1A ",
        file: '/charts/tokyo/sqd/star.jpg',
        runways: [],
    },
]
export { charts, type Chart }

